[package]
name = "moontime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
config = "0.13.4"
pretty_env_logger = "0.5.0"
rust-spice = { version = "0.7.8", features = ["download", "lock"] }
serde = { version = "1.0.195", features = ["derive"] }
serde_json = { version = "1.0.111", features = ["float_roundtrip", "arbitrary_precision"] }
tokio = { version = "1.35.1", features = ["full"] }
warp = { version = "0.3.6", features = ["tls"] }
